spring:
  application:
    name: Boot_Mini_Proj11_Profiles-Multple_YML-Files
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521/ORCL
    username: 'system  '
    password: tiger
  spring:
    datasource:
     type: oracle.ucp.jdbc.PoolDataSourceImpl
