# Conversion to YAML from Properties formar report
# Warnings:
# - The yaml file had comments which are lost in the refactoring!
spring:
  application:
    name: Boot_Mini_Proj11_Profiles-Multple_YML-Files
  profiles: 
    activate: prod 
--- 
#efine dev profile
spring:
  config:
    activate:
     on-profile: dev 
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///ntspbms717db
    username: root
    password: root
    datasou: rce.type=org.apache.tomcat.jdbc.pool.DataSource
---
#Define test profile
spring:
 config: 
   activate: 
    on-profile: test
   datasource:
     driver-class-name: com.mysql.cj.jdbc.Driver
     url: jdbc:mysql:///ntspbms717db
     username: root
     password: root  
     type: com.mchange.v2.c3p0.CombooledDataSource		
---
#Define prod profile		
 spring:
 config:
  activate:
    on-profile: prod  
  datasource: 
     driver-class-name: oracle.jdbc.driver.OracleDriver
     url: jdbc:oracle:thin:@localhost:1521/ORCL
     username: system
     password: tiger 
---		 		 
#Define uat profile
spring:
  config:
    activate:
      on-profile: uat	
      datasource:
        driver-class-name: oracle.jdbc.driver.OracleDriver
        url: jdbc:oracle:thin:@localhost:1521/ORCL
        username: system
        password: tiger
				
		
	 
